### ISSUE TITLE
--help does not show help text.

### ISSUE THREAD

**Issue by lukasoppermann** [sindresorhus/meow#105]
Hey @sindresorhus,

very neat package, thank you for writing it. 👍 

Somehow when I run `--help` I only get the following output:

```
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

However when I run `cli.showHelp()` I get the correct help text that I defined before. AM I doing something wrong here?

**Comment by niktekusho** [comment]
Without code that I/we could look at, it's hard to say what's wrong. I've used this package for a few projects now, and I didn't have any problem regarding the "predefined" flags.
