### ISSUE TITLE
Add a option for specify flags case

### ISSUE THREAD

**Issue by LitoMore** [sindresorhus/meow#106]
What about add option to change the case for flags?

Or allow users using another case?

Like this:

```javascript
const cli = meow('', {
  flagCase: 'snakecase'   // Or other cases
});
```

**Comment by sindresorhus** [comment]
I think your use-case is too obscure to handle here. You can easily use https://github.com/bendrucker/snakecase-keys yourself.

**Comment by shirshak55** [comment]
@sindresorhus hey sorry but any reason to change flags felt so weird initially that i had used snake_case and found in docs it convert to camelCase ? How to disable camelCase so meow don't touch the flags?

**Comment by sindresorhus** [comment]
You cannot disable it. The convention for JS is camelcase. I don't see any point in supporting anything other than what the majority uses.

**Comment by shirshak55** [comment]
hmm alright  Is there any chance to disable auto camel casing. Most of the POSIX api don't use camel case of arguments and it is just confusing on one side it is not camel case but in js suddenly it becomes camel case. I just wish there would be global option to remove this behavior. And camel case on long names seems so weird anyway.

`https://commons.apache.org/proper/commons-cli/`

Thank you.
