### ISSUE TITLE
Rename `alias` option to `shortFlag`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#109]
I never liked the `alias` wording, which was inherited from `minimist`. I think it would be better to have a more explicit and semantic name called `shortFlag`.

We could then also add a `aliases` option where users can specify actual aliases and not just limited to one:

```js
{
	flags: {
		unicorn: {
			type: 'string',
			default: 'love',
			shortFlag: 'u',
			aliases: [
				'--rainbow',
				'-r'
			]
		}
	}
}
```

Could use some feedback on this proposal.

**Comment by jenbuzz** [comment]
Why not just "short"?

**Comment by sindresorhus** [comment]
I think `short` can be ambiguous. It's clear in this issue description, but not so much if you just read the code without knowing the context behind it.

**Comment by LitoMore** [comment]
I think the `shortFlag` is redundant, only `aliases` just be fine.

```javascript
{
	flags: {
		unicorn: {
			aliases: ['-u']
		}
	}
}

// same with

{
	flags: {
		unicorn: {
			shortFlag: 'u'
		}
	}
}
```

**Comment by sindresorhus** [comment]
@LitoMore It's not. `shortFlag` is there to semantically indicate what's the short version of the flag. `aliases` is just any kind of alias long/short/medium/thin/thick/unicorny. This distinction will be especially important when we start generating the help output.

**Comment by LitoMore** [comment]
> `shortFlag` is there to semantically indicate what's the short version of the flag. `aliases` is just any kind of alias long/short/medium/thin/thick/unicorny. This distinction will be especially important when we start generating the help output.

Good point. I agree.

**Comment by benfletcher** [comment]
```
{
	options: [
		{
			flags: ['unicorn', 'u'],
			type: 'string',
			default: 'love',
		},
		{
			flags: ['force', 'f'],
			type: 'boolean',
		},
	}
}
```

This flattens the structure and eliminates a need entirely for a second term altogether. 'Options' is a little confusing here, admittedly, since it lives inside the Meow options object. I propose that word however, to be consistent with CLI terminology: a CLI has arguments and options. Options are specified by 'flags'.

**Comment by sindresorhus** [comment]
@BendingBender That would be a big breaking change and IMHO not for the better. I also want to make a clear distinction between an alias and a short-flag.
