### ISSUE TITLE
Only show version/help when `cli.input.length === 0` is true

### ISSUE THREAD

**Issue by LitoMore** [sindresorhus/meow#113]
Hi, it's a feature request!

I'm working on this issue: https://github.com/sindresorhus/latest-version-cli/issues/2.

About this case:

```bash
$ latest-version npm --version=beta
```

I think `meow` should not print the version if `cli.input.length === 0` is `false`.

Although we already have the `autoVersion` option, but if we turn it to `false` we have to handle the `showVersion` manually.

**Comment by sindresorhus** [comment]
I agree. Same with `--help`. PR welcome.
