### ISSUE TITLE
Missing TypeScript declaration file

### ISSUE THREAD

**Issue by screendriver** [sindresorhus/meow#119]
It [should be](https://github.com/sindresorhus/meow/blob/master/package.json#L20) there but the version that is published on `npm` just have a

```js
"files": [
  "index.js"
]
```

**Comment by sindresorhus** [comment]
You are assuming `master` is always published. That's rarely the case. For the current release, you can use `npm i @types/meow`.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/meow/releases/tag/v6.0.0
