### ISSUE TITLE
Outputs "undefined" if there is no description

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/meow#12]
I don't want to output my package.json description at the top of my CLI's help text. There's no obvious way to disable this.

I tried passing in a custom pkg object, omitting the description field:

```js
import meow from 'meow';
import pkg from '../package.json';

const cli = meow(`
  Blah blah blah.
`, {
  pkg: {version: pkg.version}
});
```

...but this results in:

```sh
$ foo --help
  undefined

  Blah blah blah.
```

I guess I could set the description to `""` but that feels like a hack and leaves an extra newline.

This is a nice little library btw!

**Comment by sindresorhus** [comment]
Why would you not want to show the description? It's a nice UX for the users.

**Comment by callumlocke** [comment]
Sure, but I want to write my own description inside my help text, not necessarily identical to the one in package.json.

The pkg description is written for things like npm search results. If someone has already installed the app and is asking for help on the command line, it's a different context imo and calls for a more practical introduction sentence. In some cases anyway.

**Comment by callumlocke** [comment]
(I agree inserting the pkg description is a sensible default though)

**Comment by sindresorhus** [comment]
That's a good point. Didn't think of that use-case.
