### ISSUE TITLE
Can't run meow on the repl

### ISSUE THREAD

**Issue by zzyyxxww** [sindresorhus/meow#125]
Action: Run `require('meow')` from a node repl in node v12.7.0
Expected: no errors
Actual: Error `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object`

Caused by module.parent.filename being null at https://github.com/sindresorhus/meow/blob/master/index.js#L15

I made it work locally by using this code instead:
```javascript
let parentDir = ''
if (module.parent && module.parent.filename) {
  parentDir = path.dirname(module.parent.filename);
}
```
and it does work, but I'm not sure if that's a good solution since `parentDir` is used as `cwd`.

**Comment by brandonpittman** [comment]
Having similar issue when compiling with @zeit/ncc.
