### ISSUE TITLE
Support ES module scripts?

### ISSUE THREAD

**Issue by dimaqq** [sindresorhus/meow#130]
I've tried writing a silly deploy script as an ES module, now that node has experimental support, but meow doesn't grok this:

```
> yarn deploy
yarn run v1.21.0
$ node src/__scripts__/deploy.mjs
(node:5588) ExperimentalWarning: The ESM module loader is experimental.
myproj/node_modules/meow/index.js:15
const parentDir = path.dirname(module.parent.filename);
                                             ^

TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (myproj/node_modules/meow/index.js:15:46)
```

I'm curious of meow really needs to look up the parent module?
If it's part of meow's magic, is there perhaps a work-around?

In my case, my script is a tiny part of a larger project, and at present I can't / don't want to invoke meow on the top-level thing. Instead I'm trying to write a tiny script that only happens to be the directory structure of `myproj`.

Is `meow` not a good fit here, or am I just missing something?

**Comment by sindresorhus** [comment]
Meow needs to read the package.json of your project. It uses that to output version and help info automatically. Even if we fix the `TypeError: Cannot read property 'filename' of undefined` thing, you would have to manually pass in the contents of package.json using the `pkg` option. I think we could add support for passing in `import.meta.url` to the `pkg` option to let `meow` know where to resolve the package from.

**Comment by GMartigny** [comment]
Would it be possible to get the same value as `module.parent.filename` from `process.argv[1]` ?

The value of `process.argv[1]` should always be the CLI tools that use Meow. Problem is, it's possible to mess with the value of `process.argv`. But apart from breaking the meow output, I can't see any security issue (it's not my expertise domain I admit).

**Comment by sindresorhus** [comment]
I think we could just use `process.mainModule.path` to get the directory of the entry module (the CLI).

**Comment by jimthedev** [comment]
I've got this one.

**Comment by jimthedev** [comment]
Sadly looks like process.main is undefined until meow transitions over so ultimately we will need people to use pkg until then if they are using es modules.

**Comment by jimthedev** [comment]
Turns out you can actually use this module in ES Modules as it exists, you just need to use some special syntax (createRequire) when importing it as shown in my PR.
