### ISSUE TITLE
Support auto use of `update-notifier`?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/meow#133]
Is it a good idea to add automatic use `updateNotifier.notify()` ? 

Maybe behind a option `update`, set `false` to disable it, set `true` to use default.

Also support custom options object , accept `updateNotifier` options, and `notifier.notify` options(maybe disable notify with `{notify: false}`?)

```js
meow('', {
  update: {
   updateCheckInterval: 1000 * 60 * 60 * 24 * 7, // 1 week
   defer: true, 
  }
})
```

maybe also a method `cli.update` to check manually

```js
const cli = meow(... , {update: false})

// call this any time you like
cli.update({updateCheckInterval: 1000 * 60 * 60 * 24 * 7, defer: true})
```

**Comment by sindresorhus** [comment]
I have considered this previously, but `update-notifier` is a heavy dependency and I don't think update notifications is something every CLI needs. I mostly use `meow` for smaller CLIs where the benefit is not that big. Also, adding `update-notifier` manually is barely two lines of code. I think it's better to just add it explicitly if you need it.
