### ISSUE TITLE
dependency @types/minimist - warning

### ISSUE THREAD

**Issue by JhonnyJason** [sindresorhus/meow#139]
Hello, 

Github is telling me about security vulnerability of minimist.

This is due to the dependency on @types/minimist.
I do assume that the dependency on @types/minimist is not a problem at all^^ - still the warning is annoying.

Is there an easy fix - maybe a place tell github, to check for the exact dependency and not a substring of it? XD

Cheers!

**Comment by sindresorhus** [comment]
https://support.github.com/contact

**Comment by JhonnyJason** [comment]
Yhea I know xD the quick decision to write here^^...
Thanks I will do so!

**Comment by sherbst** [comment]
Had the exact same issue here, in a GitHub action. I solved it by using node v16
Wanted to post here for others looking for the same issue
