### ISSUE TITLE
meow does something strange with GL

### ISSUE THREAD

**Issue by mifi** [sindresorhus/meow#144]
I create a new directory then `yarn add gl meow`

```js
const GL = require('gl');
const meow = require('meow');

// meow('foo');

const gl = GL(800, 600);
console.log(gl != null);
```

This prints `true` - all ok.

However when I uncomment `meow('foo')`, I get `false`. So for some reason `GL` returns null now. Will look more into it, but maybe you have an idea. Is meow doing any global changes to the node environment?

**Comment by sindresorhus** [comment]
The only thing I can think of is https://github.com/sindresorhus/meow/blob/2954ed2e2f614952413abb91d9ee2f5286bac511/index.js#L13-L15. Try commenting that out.

**Comment by mifi** [comment]
I tried to comment out the "delete" line, didn't help

**Comment by papb** [comment]
Hello, I happen to watch this repository and this issue surprised me. I tried to reproduce it but could not. I got `true` as output in both cases. The only difference is that I used npm instead of yarn.

**Comment by mifi** [comment]
I did some binary search code elimination and I found that what's causing it is this line:

https://github.com/sindresorhus/meow/blob/master/index.js#L80

**Comment by mifi** [comment]
Now I found this issue: https://github.com/stackgl/headless-gl/issues/180

**Comment by mifi** [comment]
As suggested there I upgraded to node v12.16.2 and now it works. I was running v12.11.1 before.

**Comment by papb** [comment]
I am on windows, node v12.14.1
