### ISSUE TITLE
Looks like `module.parent` is deprecated

### ISSUE THREAD

**Issue by papb** [sindresorhus/meow#157]
I just saw it in the [Release Notes for Node v14.6.0](https://github.com/nodejs/node/releases/tag/v14.6.0). PR: https://github.com/nodejs/node/pull/32217

It is used here:

https://github.com/sindresorhus/meow/blob/fa2a3746acba0d68297685066ec665b88671db31/index.js#L13-L15

**Comment by aduh95** [comment]
Note that `module.parent` is `undefined` when the module is loaded by something other than required from a CJS module (E.G.: `await import('meow')` or `import meow from 'meow'`), in which case the line 15 would throw (as reported in #130).

The [deprecation note](https://nodejs.org/docs/latest/api/deprecations.html#deprecations_dep0144_module_parent) gives an alternate syntax to be able to get to the parent modules without altering the CJS cache:

```js
const moduleParents = Object.values(require.cache)
  .filter((m) => m.children.includes(module));
```

Not sure if that would work here though; if there are several modules that loads `meow`, I don't think there is a reliable way to assess which made the call…

Ultimately, it seems to me there are three ways of looking at it:
- keep using `module.parent` even though it's deprecated. It's been around for so long, chances are it will never go away. The workaround for ESM users is a bit ugly, but it works and it is well documented.
- make a breaking change to the API, and request users to provide the dir path themselves (either by `__dirname` or `import.meta.url`) when calling `meow()`.
- Use the alternate syntax involving `require.cache` and `module.children`, and give up if `meow` has been loaded by more than one module. If several modules tries to load it, they need to provide the dir path in the options.

**Comment by sindresorhus** [comment]
> make a breaking change to the API, and request users to provide the dir path themselves (either by __dirname or import.meta.url) when calling meow().

This is the best solution.
