### ISSUE TITLE
isMultiple string flag is matching also the input arguments

### ISSUE THREAD

**Issue by dfernandez79** [sindresorhus/meow#160]
I have a flag (called `multiple`) with a string `type` and the `isMultiple` flag. When I use that flag with an input argument, the input argument is now part of the flag values. This doesn't happen if you put the flag at the end.

### Example code
Test repo: https://github.com/dfernandez79/ismultiple-flag-example

```js
const meow = require('meow');
const cli = meow('This is a test. Try --multiple=string inputArg', {
  flags: {
    multiple: {
      type: 'string',
      isMultiple: true,
    }
  }
});

console.log('Input: ', cli.input);
console.log('Multiple: ', cli.flags.multiple)
```

### Outputs
```
➜ node . --multiple=string inputArg
Input:  []
Multiple:  [ 'string', 'inputArg' ]
```

```
➜ node . inputArg --multiple=string
Input:  [ 'inputArg' ]
Multiple:  [ 'string' ]
```

**Comment by sindresorhus** [comment]
// @ulken

**Comment by ulken** [comment]
Haven't looked at the code, but as I recall we allow (`isMultiple`) values to be space separated, which is why `inputArg` is swallowed by the flag. 

As I see it, we have two options:

1. Introduce a breaking change by not allowing space (only comma) as a separator.
2. Force users to explicitly use `--` to distinguish flag values from input args. 

How do we want this to work?

**Comment by ulken** [comment]
Not sure if it would work, but maybe require wrapping the argument in quotes if one wants to space separate values? Then we could only consume the first argument and split it on whitespace.

**Comment by ulken** [comment]
I won't have a look at it until it's been decided what the desired behavior is here.

**Comment by dfernandez79** [comment]
When I submitted the bug, I didn't know that this was the expected behavior. It seems that yargs works in a similar way with array flags.

I can workaround my CLI app by splitting a single value flag. 

I understand if there is no desire to change it. As user of the CLI I found this behavior to be unexpected, because double dash usually means do not parse the rest. My expectation for the multiple flag was something like: `--flag=val1 --flag=val2` or `--flag=val1,val2`.

It's ok for me to close the bug, if the behavior is by design.

**Comment by ulken** [comment]
Yes, you're right regarding `--`, so that's not a valid solution.

The examples you list should still work though. Or are you saying it parses `inputArg` even though you use comma-separated syntax? If so, then _that's_ a bug 🐛.

**Comment by ulken** [comment]
@sindresorhus What say you? Change or close?

**Comment by sindresorhus** [comment]
> but as I recall we allow (isMultiple) values to be space separated

I must have missed that when merging the PR. I agree, with @dfernandez79 that it's not what the user would expect, and neither would I.

**Comment by sindresorhus** [comment]
> Introduce a breaking change by not allowing space (only comma) as a separator.

I think it's worth doing a major release to fix this.

**Comment by ulken** [comment]
> > but as I recall we allow (isMultiple) values to be space separated
> 
> 
> 
> I must have missed that when merging the PR. I agree, with @dfernandez79 that it's not what the user would expect, and neither would I.

Then I apologize for introducing it. No excuse, but I got it from one of the previous PR attempts.

**Comment by sindresorhus** [comment]
@ulken I was not blaming you, FWIW.

**Comment by ulken** [comment]
Fix the first half of the issue, i.e. not greedily consume array flag arguments. I'll make a separate PR for supporting comma-separated values.

**Comment by ulken** [comment]
Gave it a go, but did not end up well. I could easily make it work for `string-array`, but it would be unintuitive to only support that.

I used the [`coerce`](https://github.com/yargs/yargs-parser#parserargs-opts) option to split array flag arguments on `,`, which works fine for strings. Unfortunately, for `number-array` and `boolean-array` the values have already been type coerced when passed to the `coerce` function (yielding `NaN` for numbers and `true` for booleans) and thus there's no `,` left to split on...

**Comment by ulken** [comment]
Open issue in `yargs` to support comma-separated values: https://github.com/yargs/yargs/issues/846

**Comment by ulken** [comment]
If we _really_ want to support comma separated values, I suppose we could convert all array types to `string` and then manually coerce them to `number` or `boolean`.

**Comment by ulken** [comment]
No, that's not a viable option either. It ends being really brittle having to handle defaults etc. (apart from handling type coercion).

**Comment by sindresorhus** [comment]
> If we really want to support comma separated values, I suppose we could convert all array types to string and then manually coerce them to number or boolean.

Nah. We can wait for Yargs to implement it: https://github.com/sindresorhus/meow/issues/164
