### ISSUE TITLE
`isMultiple` should result in an empty array when the flag is not specified

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#161]
Currently, it returns `undefined`, which is incorrect.

I had to work around it here: https://github.com/sindresorhus/replace-in-files-cli/commit/e9ac8819c054eda48e2b273c1ee31ff0164f0b08#diff-2cce40143051e25f811b56c79d619bf5R63

// @ulken

**Comment by felizj17** [comment]
I would like to give this a go

**Comment by felizj17** [comment]
wait nvm i mightve asked for more than i can chew, ill just wait and see how this is solved, sorry just starting out

**Comment by ulken** [comment]
Noted. I'll have a look 👀 in the coming days if nobody picks it up before that.

**Comment by ulken** [comment]
Took a stab at it
