### ISSUE TITLE
Turn off cli args type detection by default

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#17]
Can be turned on in an option.

I've had so many problems with it.

The latest: https://github.com/chalk/chalk-cli/pull/2

What should the option be named?

-

Note to self: Remove all instances of `string: ['_']` in my modules when this is done.

**Comment by SamVerschueren** [comment]
:+1: Having the same issue when providing a numeric username in `dev-time-cli`.

**Comment by nevilgeorge** [comment]
Are we thinking of parsing everything as strings? Can the option be something like --type? I think I can help, with some more guidance!

**Comment by sindresorhus** [comment]
Yes, with a `meow` option to turn on type detection again, but should be off by default.

**Comment by SamVerschueren** [comment]
What are the possibilities here?

- `typeDetect`
- `autoDetect`
- `type`
- `autotype`
- `types`

**Comment by sindresorhus** [comment]
- `inferType`

**Comment by SamVerschueren** [comment]
Works for me :)
