### ISSUE TITLE
Breaking change introduced in version 8.1.1

### ISSUE THREAD

**Issue by nimrodolev** [sindresorhus/meow#173]
Hi,

You've just released version 8.1.1 that includes [this change](https://github.com/sindresorhus/meow/commit/1609709e24b58bd0492b5b1746a05684a8eed183) which is breaking for any scripts using argument names with hyphens.

[Here's the issue that got me here](https://github.com/conventional-changelog/conventional-changelog/issues/735)

If this behaviour is inentinal it would be great if you could revert these changes and re-release them with  a bumped *major* so they don't get automatically consumed by anyone using `"meow": "^8.0.0"`

**Comment by sindresorhus** [comment]
That change only validates the existing behavior though. So `conventional-changelog` is using the incorrect config. But fair enough. Reverted the change and published 8.1.2.

**Comment by sindresorhus** [comment]
Major release: https://github.com/sindresorhus/meow/releases/tag/v9.0.0

**Comment by spenceclark** [comment]
Thanks. This was also casing an issue with our CI process. I appreciate the quick resolution.

**Comment by nimrodolev** [comment]
Thanks for the quick fix, @sindresorhus - CI pipelines all over the world thank you 😄
