### ISSUE TITLE
When flag name and alias name are the same, the flags object does not contain this property even with default

### ISSUE THREAD

**Issue by GentileFulvio** [sindresorhus/meow#174]
```js
import * as meow from 'meow';

const cli = meow(
	`
	Usage
	  $ test <input>

	Options
	  --concurrency, -c  C

	Examples
	  $ test --concurrency=5
`,
	{
		flags: {
			concurrency: {
				type: 'number',
				alias: 'c',
				default: 5
			},
			cwd: {
				type: 'string',
				alias: 'cwd',
				default: process.cwd()
			}
		}
	}
);
```

`cli.flags.cwd` is `undefined`.

**Comment by sindresorhus** [comment]
Why are you defining `alias` the same as the flag name?

**Comment by Caesarovich** [comment]
@GentileFulvio The `alias` option is optional. If you don't have any alias different than the command's name, there is no point defining it.

@sindresorhus I think this can be closed considering lack of activity and high probabilities that the option was just misunderstood.
