### ISSUE TITLE
Cannot read package information if using meow in ESM

### ISSUE THREAD

**Issue by LitoMore** [sindresorhus/meow#176]
`meow` is using `module.parent.filename` as `parentDir` to read package info:

```js
const parentDir = path.dirname(module.parent && module.parent.filename ? module.parent.filename : '.');
```

But in ESM, we cannot use [`__filename`](https://nodejs.org/dist/latest/docs/api/esm.html#esm_no_filename_or_dirname) anymore.

Do you have any plan move this package to ESM?

@sindresorhus And I wonder how you would solve this problem?

**Comment by LitoMore** [comment]
We can resolve #125 at the same time.

**Comment by sindresorhus** [comment]
Yeah. PR welcome to move `meow` to ESM.

See:
- https://github.com/sindresorhus/quick-lru/commit/a408ce9b3ad430607f1f3e3077d1d21636343015
- https://github.com/sindresorhus/meta/discussions/15

**Comment by LitoMore** [comment]
I'm going to use this code below to instead CommonJS module's  `__filename`:

```javascript
import {fileURLToPath} from 'url';

const __filename = fileURLToPath(import.meta.url);
```

**Comment by sindresorhus** [comment]
This is not fixed until we support the package.json reading.

**Comment by LitoMore** [comment]
I tested this issue on the `main` branch and looks good.

Is there any edge case that will cause the read package issue?

**Comment by sindresorhus** [comment]
I'm not sure what you're asking. You removed the old workaround for clearing the require cache. We now need to allow the user to pass in `import.meta` somehow to be able to know the meow consumer's CWD.

**Comment by LitoMore** [comment]
Oh, I see. Let me continue on this work.
