### ISSUE TITLE
Feature request: Restore `process.title` on exit

### ISSUE THREAD

**Issue by fisker** [sindresorhus/meow#179]
`process.title` should be restored when exiting.

**Comment by sindresorhus** [comment]
Why?

**Comment by fisker** [comment]
`del-cli dist/** && some-other-cli-do-not-set-title`

**Comment by sindresorhus** [comment]
This sounds like an issue with your terminal. What terminal are you using? If not, it's a problem with Node.js, not `meow`. The `process.title` docs say it sets the name for the current process.

**Comment by fisker** [comment]
Thanks, I'll take a deeper look. Close for now.
