### ISSUE TITLE
Can't work on "module" package

### ISSUE THREAD

**Issue by fisker** [sindresorhus/meow#180]
When cli is "module", [this line](https://github.com/sindresorhus/meow/blob/5400b667125d91f3256b8f074b07aea096b4c32f/index.js#L16) will fail.

**Comment by sindresorhus** [comment]
It's working fine for me: https://github.com/sindresorhus/to-double-quotes-cli/blob/c6286625d06140f35f1138597a125fb353497a09/package.json#L13

We do need to remove that line for when `meow` moves to ESM, but `meow` should be fully ESM compatible already as ESM can import CommonJS.

https://github.com/sindresorhus/meow/issues/176

**Comment by fisker** [comment]
Sorry, I should search first.
