### ISSUE TITLE
Incompatibility with ts-node

### ISSUE THREAD

**Issue by QuentinRoy** [sindresorhus/meow#188]
I could not find a way to make v10 to work with ts-node and had to revert to v9.

I went through [this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), then [this](https://github.com/TypeStrong/ts-node/issues/1007), but when following the later, `import.meta` does not exist anymore. I could not find any other solution. This is possibly a `ts-node` issue rather than a `meow` issue, albeit it may be worth mentioning it somewhere and save hours to anyone like me trying to make it work.

**Comment by cspotcode** [comment]
Seems to work well.
https://github.com/TypeStrong/ts-node-repros/tree/meow-188
https://github.com/TypeStrong/ts-node-repros/runs/2943187328

You can compare the example I have linked above to your own code.  Perhaps you misconfigured something.

**Comment by QuentinRoy** [comment]
Thank you! I finally made it work. I am not sure what did not work before, but I think it is because I use `"module": "system"` (does not work), and did not add the `.js` extension when importing local modules.
