### ISSUE TITLE
read read-pkg-up feels very bloated...

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/meow#196]
Regarding this function and `read-pkg-up`

https://github.com/sindresorhus/meow/blob/e1f0e24840634ae58664a70ee9e19ab80166b3f3/index.js#L112-L115

It felt very unnecessary to install 39 packages and 674 KB of data for just trying to read the closest package.json file

Tried to come up with a pure js solution...
```js
import fs from 'node:fs'

let path = import.meta.url.slice(7) // remove `file://`
let pkg
while (!pkg && path) {
  path = path.substr(0, path.lastIndexOf('/')) // get parent dir
  try {
    pkg = JSON.parse(fs.readFileSync(path + '/package.json'))
  } catch (_) {}
}
console.log(pkg)
```

This is all the sub dependencies it have to install
https://npmgraph.js.org/?q=read-pkg-up
![image](https://user-images.githubusercontent.com/1148376/130060648-37f2a219-d06c-41d4-8108-9c07e0f46bf1.png)

**Comment by sindresorhus** [comment]
I'm willing to switch it to https://github.com/sindresorhus/find-up, but I think the best solution is just bundling dependencies and treeshaking (there's another issue for that).

**Comment by sindresorhus** [comment]
Bunding was done and the `read-package-up` dependency is now much smaller.
