### ISSUE TITLE
Meow is only being tested on Node 16 on CI

### ISSUE THREAD

**Issue by fregante** [sindresorhus/meow#199]
https://github.com/sindresorhus/meow/blob/075f96f80111548ea07afb413b197070244386fe/.github/workflows/main.yml#L12-L13

Even thought the package is marked as compatible with v12

https://github.com/sindresorhus/meow/blob/075f96f80111548ea07afb413b197070244386fe/package.json#L15-L17

**Comment by sindresorhus** [comment]
It's because of https://github.com/xojs/xo/issues/555
