### ISSUE TITLE
Configurable version option

### ISSUE THREAD

**Issue by am11** [sindresorhus/meow#2]
In node-sass, we want to print both node-sass and libsass (the base lib) versions when user queries `node-sass --version` (or even `node-sass -v`) like so:

> node-sass version: 2.0.1
libsass version: 3.1.0

without changing the semver `"version": "2.0.1",` in package.json.

Please make the version option configurable in addition to the default behavior (`console.log(pkg.version)`).

**Comment by kevva** [comment]
Would work with something like `console.log(opts.version || pkg.version)`.

**Comment by sindresorhus** [comment]
You can now either supply a custom string to the `version` option or `false` to handle it yourself.

**Comment by am11** [comment]
Awesome! Thank you. :tada:
