### ISSUE TITLE
How to use with commonjs?

### ISSUE THREAD

**Issue by henhal** [sindresorhus/meow#204]
It seems ìmportMeta` is mandatory, but `import.meta` is only available if `module` is `es2020` etc.

If using `meow` from a package using `module: commonjs`, what should be passed as `importMeta`?

TBH I'm not sure what `importMeta` is used for so I couldn't immediately understand how to tackle this.

**Comment by sindresorhus** [comment]
Meow requires ESM.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
