### ISSUE TITLE
ExperimentalWarning when using Meow with modules

### ISSUE THREAD

**Issue by GBrachetta** [sindresorhus/meow#220]
I'm using Meow in a CLI  which uses modules rather than common imports (`import meow from 'meow'`), and I get a warning when, for example, I use the built-in `--version` flag, saying that importing JSON modules is an experimental feature:

```
(node:83927) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

Obviously this pollutes the output.

Is there a way to hide this warning?

**Comment by sindresorhus** [comment]
I'm unable to reproduce this. What Node.js and Meow version?

**Comment by sindresorhus** [comment]
Closing as this is not a problem with Meow.

**Comment by sindresorhus** [comment]
Meow returns the package data, so not sure why you are importing it yourself.
