### ISSUE TITLE
Expose package.json version as property

### ISSUE THREAD

**Issue by joeykilpatrick** [sindresorhus/meow#224]
Would be nice if there was access to the package version like so:

```typescript
const cli = meow(`
    ...
`, {
    importMeta: import.meta,
});

const version: string = cli.version;
```
I know `cli.showVersion()` is available, but it prints the string instead of returning it. Without this feature, the `package.json` must be parsed separately, which this package is already doing internally.

Alternatively, this package could expose the entire parsed `package.json`.

Would be more than happy to submit a PR.

**Comment by sindresorhus** [comment]
This is already available: `cli.pkg`

**Comment by tommy-mitchell** [comment]
@sindresorhus I think it could be worth adding something like a `cli.pkgVersion`. There’s been a few discussions about moving away from `read-pkg-up` or lazy parsing `package.json` when `cli.pkg` is first accessed for performance; having a quick access for the version number could be beneficial.

**Comment by sindresorhus** [comment]
How is `cli.pkgVersion` better than just `cli.pkg.version` when `cli.pkg` is lazy?

**Comment by tommy-mitchell** [comment]
You’re right, didn’t fully consider that.
