### ISSUE TITLE
Question: huge bundle size?

### ISSUE THREAD

**Issue by so1ve** [sindresorhus/meow#236]
On bundlephobia, it show meow is 49.4kB (minified and gzipped). https://bundlephobia.com/package/meow@11.0.0
However, commander is only 9.4kB. https://bundlephobia.com/package/commander@10.0.1

**Comment by voxpelli** [comment]
This is a module used to create CLI:s, is the bundle size relevant?

**Comment by so1ve** [comment]
> This is a module used to create CLI:s, is the bundle size relevant?

I think the bundle size is important because users may spend more time installing. But yes, it is a CLI helper, so the size may not be too important.
