### ISSUE TITLE
Choices?

### ISSUE THREAD

**Issue by joshuavachon25** [sindresorhus/meow#237]
I'm currently using meow 11.0.0 to make a CLI and I saw in the doc that we could user choices with the flag to limit valid values, but it doesn't work. Is it an old functionnality?

Example:
If I try: unicorn -r -e cat
I won't get an error even if cat is not in the choices.

Code: 
```js
env: {
            type: 'string',
            choices: ['dev', 'int'],
            alias: 'e',
            isMultiple: true,
            isRequired: (flags) => {
                if (flags.run) {
                    return true;
                }
                return false;
            }
        },
```

**Comment by sindresorhus** [comment]
The option is not released yet. The readme reflects the `main` branch, not the latest version.

**Comment by joshuavachon25** [comment]
Thanks!
