### ISSUE TITLE
Feature Proposal - Disable Indent

### ISSUE THREAD

**Issue by dylanarmstrong** [sindresorhus/meow#240]
I'd like the option to disable the indent.

```
  Some descriptive text
  Usage:
    $ application
```

Is the default, and I'd like to make it indented to 0.

Proposal:
Add `indent` as an option with a default value of `2`.

I have submitted a PR for this.

**Comment by voxpelli** [comment]
Can you give a motivation why you want to have a different indent?

Is it personal taste or it would give some tangible improvements from your point of view?

**Comment by voxpelli** [comment]
Lets see what the maintainer thinks then, but just a reflection: There are no other such presentation options in Meow currently, and I'm personally not sure if it would be good to open that box of making presentation customizable to personal taste. Lots of options for little gain?

**Comment by dylanarmstrong** [comment]
Interesting, I hadn’t actually realized.

How frequently do they check PRs? I have another one against node-defaults too.

**Comment by sindresorhus** [comment]
Accepted.

```js
/* @default 2 */
indent: number | false
```

**Comment by sindresorhus** [comment]
> How frequently do they check PRs? I have another one against node-defaults too.

Every day, but I have been at bit overwhelmed with pull request during the summer.

**Comment by sindresorhus** [comment]
`indentHelp` or `helpIndent`? I think `indent` is too ambigious. We don't indent `--version`, for example.

**Comment by voxpelli** [comment]
`helpIndent` I would say

ons 30 aug. 2023 kl. 09:03 skrev Sindre Sorhus ***@***.***>:

**Comment by dylanarmstrong** [comment]
Thanks, I've updated PR to `helpIndent`.

**Comment by dylanarmstrong** [comment]
Just to clarify, this was updated in the PR.

**Comment by dylanarmstrong** [comment]
Hi, any update on this?
