### ISSUE TITLE
`meow(...).flags` is `any` in 12.1.0

### ISSUE THREAD

**Issue by melusc** [sindresorhus/meow#244]
With version <https://github.com/sindresorhus/meow/tree/v12.1.0> `type-fest` is not declared as a dependency anymore in the actual published package. `type-fest` then can't be resolved in [index.d.ts](https://github.com/sindresorhus/meow/blob/b412c0d78702f3fb2fff4a474007422bc78a63f9/index.d.ts#L1-L4) and `meow(...).flags` is just `any`.

I have created a repository to demonstrate the issue
- <https://github.com/melusc/meow-dep-less-issue/>
- <https://github.com/melusc/meow-dep-less-issue/actions/runs/5989672259/job/16246105667>

**Comment by sindresorhus** [comment]
// @tommy-mitchell
