### ISSUE TITLE
ESLint `import/no-unresolved` false positive when module is imported

### ISSUE THREAD

**Issue by estilles** [sindresorhus/meow#251]
While using ESLint, a false positive is triggered when:
- using ES modules
- `import/no-unresolved` is enabled
- `meow` is imported (see below)

### Example
<img width="775" alt="image" src="https://github.com/sindresorhus/meow/assets/5514878/13d58711-6bad-4ef3-86ca-b6fc8f35b158">

### Explanation
ESLint fails to detect/resolve the module because it expects the `package.json` `main` key to point to the module entry point. The existing `package.json` does include an `exports.default` key pointing to `./build/index.js`, but unfortunately it is not used by ESLint.

This is obviously just a non-urgent, quality-of-life issue, but I will submit a quick PR anyway.

### Workaround
Right now I'm mitigating this by having the `import/no-unresolved` rule ignore `meow`

```json
  "rules": {
      "import/no-unresolved": ["error", { "ignore": ["meow"] }],
  }
```

**Comment by sindresorhus** [comment]
This is a problem for the `import` plugin to resolve. I don't plan to add a `main` field to package.json.
