### ISSUE TITLE
Autocompletion?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/meow#29]
Have you guys thought about tabbed autocompletion support for commands, flags and file system? This could go to this module directly, or add a tip if there another module doing it.

**Comment by sindresorhus** [comment]
Out of scope of `meow`. Auto-complete is mostly useful for huge CLI with lots of commands, and then `meow` is the wrong choice anyways. 

Use `yargs` for larger things. See: https://github.com/bcoe/yargs#completioncmd-description-fn

**Comment by stevemao** [comment]
a separate module?

**Comment by sindresorhus** [comment]
https://github.com/f/omelette

**Comment by stevemao** [comment]
Thank you :)
