### ISSUE TITLE
stdin support?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/meow#3]
If you haven't noticed I'm having a blast here _stealing your code_ but I realized: meow has no piping support. Any plans on adding it?

**Comment by sindresorhus** [comment]
Yeah, I wasn't sure whether to add it or not. I don't always use it and I tried to keep `meow` as minimal as possible. Can you elaborate on how you'd want to use it and how it should look like API wise?

I'll consider it, but can easily just use https://github.com/sindresorhus/get-stdin though.

**Comment by bfred-it** [comment]
I have little experience with cli, so I might not be the best person to give aesthetics suggestions, but you could either make it a stream or buffer it in `cli.stdin`

I'm building an uploader that currently takes a file name:

    upload file.js

but it could also work with stdin this way:

    uglifyjs file.js | upload

Inside I'm using `http.request` so I can probably make it work as either a stream or buffer.

**Comment by arthurvr** [comment]
I'd personally like to keep meow's API landscape as clean as possible so am :-1:.  Though I see your use case, @bfred-it, I don't see why you wouldn't use get-stdin directly.

**Comment by kevva** [comment]
Ultimately, `cli.stdin` would be the same as using `get-stdin` directly and it's API is not complex at all so I don't see the need for including it here.

**Comment by sindresorhus** [comment]
I added a note in the readme.

**Comment by bfred-it** [comment]
Alright, it makes sense to use two modules! I suppose I can use meow as the main interface and add `get-stdin` to check for any `stdin` input.

Thank you!
