### ISSUE TITLE
Allow users to specify their minimist parser and/or swap out minimist for substack

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/meow#30]
I'd like to create a project like [subarg](https://github.com/substack/subarg) except move the options outside of the arg (e.g. `$ foo --plugin autoprefixer [browsers: "last 2", remove: "false"]`).

In lieu of letting us pass our own parsers, could we simply swap out minimist for subarg? It'd be the same thing except users would gain the ability to get arg specific args.

Browserify uses this so you're able to pass options within options. For instance: `browserify -t [ foo --bar=555 ] main.js`

Asking because we're working on the PostCSS CLI syntax https://github.com/postcss/postcss-cli/issues/1 and I'm trying to use Meow.

**Comment by sindresorhus** [comment]
`$ foo --plugin autoprefixer [browsers: "last 2", remove: "false"]` is really weird. You should keep it to something that are `--key val`. See https://github.com/gkz/levn for a good way to handle more advanced values (ESLint uses this too).

**Comment by corysimmons** [comment]
Since I'm not grokking levn, would you mind showing me what `$ foo --plugin autoprefixer [browsers: "last 2", remove: "false"]` would look like in it?

**Comment by sindresorhus** [comment]
```
$ foo --plugin="autoprefixer:{browsers: 'last 2', remove: 'false'}"
```

**Comment by corysimmons** [comment]
Thanks @sindresorhus Nice cowface. Feel free to join in the postcss-cli api discussion directly too. :+1:
