### ISSUE TITLE
Error helper

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#4]
Most of my CLI's have this:

```js
var cli = meow();

fn(function (err) {
	if (err) {
		console.error(err.message);
		process.exit(1);
	}
});
```

Wonder if we could abstract out the error handling.

Eg:

```js
var cli = meow();

fn('unicorn', function (err) {
	cli.handleError(err);
});
```

It could potentially also handle showing the stack when `--verbose` is passed.

Thoughts?

-

// @kevva @floatdrop @arthurvr @shinnn

**Comment by arthurvr** [comment]
Yes please! :+1:

**Comment by kevva** [comment]
Yeah, sure, that'd be useful I think. I'm using the same pattern everywhere in my CLIs too.

**Comment by sindresorhus** [comment]
How about the verbose thing?

**Comment by gillstrom** [comment]
How do we change the process.exit code?

**Comment by sindresorhus** [comment]
Maybe `cli.exitCode = 3`; and it will use that instead?

Could also be a second argument to `cli.handleError(err, exitCode);`, but then you wouldn't be able to:

```js
fn('unicorn', cli.handleError(err));
```

**Comment by kevva** [comment]
Hmm, why wouldn't that work?

**Comment by sindresorhus** [comment]
Oops, should have been:

```js
fn('unicorn', cli.handleError);
```

Might not be a problem though. Since you can just wrap it in a function, and arrow functions will make that nicer.

**Comment by kevva** [comment]
Yeah, exactly, shouldn't be that big of a deal. Better future compatibility too if we wanted to add evem more stuff.

**Comment by LinusU** [comment]
`err.exitCode`? That's what [express is doing](https://github.com/expressjs/errorhandler/blob/bbeba05924aeaa2429a3bcef8a83282cd8ba740f/index.js#L84-L87)

```javascript
var err = new Error('Output file exists')
err.exitCode = 9
err.code = 'EEXISTS'
cli.handleError(err)
```

**Comment by sindresorhus** [comment]
Skipping this as we now handle promise errors automagically and I'm not going to continue using callback-style interface.
