### ISSUE TITLE
Using meow probably breaks Electrons launch-process

### ISSUE THREAD

**Issue by florianb** [sindresorhus/meow#40]
I'm using meow to parse any cli-options and decisively exit the launch, showing the help:

```
const _ = require('lodash');
const meow = require('meow');

module.exports = () => {
	const cli = meow(`
		Options:

		Usage:
`);

	if (_.isArray(cli.flags) &&
		_.includes(cli.flags, 'help')
	) {
		cli.showHelp(0);
	}

	return cli;
}
```

This generates the following Warnings in the console and the `ready`event gets never fired:
```
node v5.10.0
electron 0.37.8
May  3 12:48:39  [99560] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
...
May  3 12:48:39  [99560] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
May  3 12:48:39  [99560] <Warning>: Invalid Connection ID 0
event 'will-finish-launching' fired.
May  3 12:48:39  [99560] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
...
```

If comment the whole export out, it runs like a glance:
```
node v5.10.0
electron 0.37.8
event 'will-finish-launching' fired.
event 'ready' fired.
```

It is probably worth mentioning, that the event-subscription happens immediately after the cli-parsing.
If there is anything i can do - give me a hint! 👋

**Comment by sindresorhus** [comment]
I don't get why you're using `meow` for this? Why not just use [`minimist`](https://github.com/substack/minimist) directly? `cli.showHelp(0);` exits the process, so obviously the `ready` wouldn't be called.

**Comment by florianb** [comment]
Good question - meow just bundles everything i needed and i didn't consider trying anything else, since i made good experiences with your libraries.

In this case `showHelp` shouldn't be called (since the help-flag isn't provided) and i do not expect the process to be halted. Calling a dedicated `process.exit()` in the rest of code doesn't lead to any problems by the way.

I guess meow is more intended to be used in pure cli-appications, i therefore will switch to minimst and close this issue.
