### ISSUE TITLE
help text is truncated after ~988 chars

### ISSUE THREAD

**Issue by rygine** [sindresorhus/meow#42]
I'm on Node 6. The output buffer isn't flushed on `process.exit()`.

It seems this problem was already encountered in `eslint` and fixed here: https://github.com/eslint/eslint/blob/master/bin/eslint.js#L80

I've applied a quick fix to my local copy and the issue goes away. The unit test for checking help output does not catch this issue after updating the fixture with very long help text.

**Comment by sindresorhus** [comment]
Yup, lots of people are trying to resolve it in Node.js: https://github.com/nodejs/node/issues/6456#issuecomment-219102451

**Comment by rygine** [comment]
https://github.com/yargs/set-blocking

a fix?

**Comment by sindresorhus** [comment]
Node.js 6.2.1:

> tty: Default to blocking mode for stdio on OS X. A bug fix in libuv 1.9.0, introduced in Node.js v6.0.0, exposed problems with Node's use of non-blocking stdio, particularly on OS X which has a small output buffer. This change should fix CLI applications that have been having problems with output since Node.js v6.0.0 on OS X. The core team is continuing to address stdio concerns that exist across supported platforms and progress can be tracked at https://github.com/nodejs/node/issues/6980. (Jeremiah Senkpiel) #6895 - https://nodejs.org/en/blog/release/v6.2.1/
