### ISSUE TITLE
can be use -h && --help

### ISSUE THREAD

**Issue by i5ting** [sindresorhus/meow#46]
just like

```
node -h
```

**Comment by sindresorhus** [comment]
There's no consistent convention of using `-h` for `--help`. Some CLI's supports it and some don't, so I feel it's safer (and clearer) to just always do `--help`. I also didn't want to use up a valuable shortflag for this. You can easily implement it yourself if you disagree:

```js
if (cli.flags.h) {
  cli.showHelp();
}
```

**Comment by i5ting** [comment]
can i make a pr to ava for support this?
