### ISSUE TITLE
version alias?

### ISSUE THREAD

**Issue by charlespeters** [sindresorhus/meow#48]
how can i alias `app -v` to be `app --version`?

**Comment by kevva** [comment]
```
const cli = meow(`
    Usage
      $ foo
`, {
    alias: {
        v: 'version'
    }
});
```

**Comment by sindresorhus** [comment]
We intentionally do not do it out of the box as it's better to enforce long flags. `-v` is also commonly used to mean `--verbose`. So you could introduce potential subtle bugs for users when they do `-v` and get version instead of verbose mode.

**Comment by charlespeters** [comment]
@kevva worked perfectly, thanks so much!
@sindresorhus that does make a lot of sense for default behavior

i really appreciate your folks clarification.
