### ISSUE TITLE
Parse Aliases

### ISSUE THREAD

**Issue by blond** [sindresorhus/meow#50]
I know that now to parse need use [aliases](https://github.com/sindresorhus/aliases) package (related #24).

One of my projects consists of scripts (about a hundred) to run in Continuous Integration.

I have to add the same lines in each file.

``` js
const aliases = require('aliases');

meow(help, { alias: aliases(help, {h: 'help'}) });
```

I think that we can add `parseAliases` option to simplify API.

``` js
const help = `
    Usage
      $ unicorn <name>

    Options
      -r, --rainbow  Lorem ipsum dolor sit amet
      -m, --magic    Aenean commodo ligula eget dolor
`;

meow(help, { parseAliases: true });
```

I'd really like to have this feature by default.

We can parse aliases if `alias` option is not specified. It won't break backward compatibility.

**Comment by sindresorhus** [comment]
I like the idea.

@SamVerschueren @kevva What do you think?

**Comment by SamVerschueren** [comment]
Adding it would make sense. But not sure about using it as default behaviour...

**Comment by sindresorhus** [comment]
@SamVerschueren Why not? I guess it's a little bit magic, but would be nice not having to define them twice.

**Comment by SamVerschueren** [comment]
Never used it before (maybe because it required another module). But I guess you're right that this makes it quite easy to add aliases and to not have to define them twice.

**Comment by blond** [comment]
Basic usability of the `meow` is that I can write help in human-readable format and do nothing more. Based on this philosophy need to parse not only arguments but also aliases.

I have invited several developers to use `meow`. Each of them asked me, "Why do we need to describe aliases twice?".

**Comment by blond** [comment]
I think that alias should extend parsed aliases.

Quite often, need to specify short aliases for `help` and `version`.

```js
const help = `
    Usage
      $ unicorn <name>

    Options
      -r, --rainbow  Lorem ipsum dolor sit amet
      -m, --magic    Aenean commodo ligula eget dolor
`;

meow(help, {
    alias: {
        h: 'help',
        v: 'version'
    }
});
```

**Comment by sindresorhus** [comment]
Alright. Let's do this. @blond Wanna do a pull request? Should have ability to turn it off with `parseAliases: false`.

**Comment by a-x-** [comment]
ping @blond

**Comment by sindresorhus** [comment]
I've come to the realization that it would be better to go the other way around. Generate CLI output from code definition. So closing this.
