### ISSUE TITLE
Support `required` flags

### ISSUE THREAD

**Issue by blond** [sindresorhus/meow#51]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/meow/issues/51)

Some options must always be specified.

I want to have a way to specify the required options in API.

**Example**

``` js
const cli = meow(`
    Usage
      $ process

    Options
      -i, --input   Input file
      -o, --output  Output file

    Examples
      $ process --input=lib/file.js --output=dest/file.js
`, {
    required: ['input', 'output']
});
```

A program without required options must quit with an error message.

```
$ process --output=dest/file.js

Missing required option:
    --input, -i  Input file
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#110 Feat/add required flags](https://issuehunt.io/r/sindresorhus/meow/pull/110)
- [#141 Implement isRequired feature as described in #51 and #110](https://issuehunt.io/r/sindresorhus/meow/pull/141)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/meow/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kevva** [comment]
In most cases I would handle this in the API. Any reason you need to do it in the CLI?

**Comment by SamVerschueren** [comment]
I agree with @kevva. I believe this should be handled by the code that is called. That allows the most flexibility with informative custom error messages.

**Comment by kevva** [comment]
Going to close for now. If there are some good arguments for having this as an option we might re-open it again.

**Comment by sindresorhus** [comment]
I'm gonna reopen this as I think it could be useful for CLI only tools (ones that don't have an API).

It could be specified like:

```js
flags: {
	rainbow: {
		type: 'boolean',
		alias: 'r',
		required: true
	}
}
```

We should be clear in the docs that API level option validation should be preferred.

**Comment by HackAfro** [comment]
If a required field takes a function, should the expected return value of the function be a boolean? A quick example could be helpful as I am currently working in this.

Thanks

**Comment by sindresorhus** [comment]
> should the expected return value of the function be a boolean?

Yes

> A quick example could be helpful as I am currently working in this.

```js
{
	flags: {
		rainbow: {
			type: 'boolean',
			required: (input, flags) => flags.unicorn === '🦄'
		}
	}
}
```

Note, I'm not exactly sure what the function arguments should be. I'm open to suggestions there. I guess the `input` and `flags`. Anything else?

---

I also think we should call the option `isRequired`, not `required`.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the previous attempt here and the feedback given: https://github.com/sindresorhus/meow/pull/110

**Comment by NSExceptional** [comment]
Can we get this, but for input (non-flag arguments)?
