### ISSUE TITLE
Parse custom `input` name

### ISSUE THREAD

**Issue by a-x-** [sindresorhus/meow#54]
```es6
const cli = meow(`
    Usage
      $ foo <bar>

    Options
      --rainbow, -r  Include a rainbow
`, {customInput: true});
/*
{
    bar: ['unicorns'], // <-----------------
    flags: {rainbow: true},
    ...
}
*/
```

**Comment by a-x-** [comment]
i have to write in all projects `cli.foo = cli.input` for convenient using

**Comment by kevva** [comment]
I'm not sure I follow you. You want the `input` key name to be configurable in the returned object? In that case, why? I don't see a use case other than a cosmetic one.

**Comment by a-x-** [comment]
now I have to write: `
    Usage
      $ foo <bar>
...
`

`const bar = opts.input`

**Comment by kevva** [comment]
I'm 👎 to be honest. It doesn't sound common enough that we want an option for it.

**Comment by a-x-** [comment]
👻
