### ISSUE TITLE
Custom Arguments Object (option.argv) not working?

### ISSUE THREAD

**Issue by F1LT3R** [sindresorhus/meow#58]
Hi there!

I'm having a little trouble figuring out how to use the documented `{argv}` option. Maybe I'm completely missing something obvious, in which case, apologies.

### argv

Type: `array`
Default: `process.argv.slice(2)`

Custom arguments object.

## Here's my code:

```javascript

const help = `
	Usage
	  $ yay

	Options
	  -r, --root Root directory
`

const cli = meow(help, {argv: ['--root', 'foo']})

// What I'm expecting...
console.log(cli.flags) // {root: 'foo'}
console.log(cli.input) // ['root', 'foo']

// What I'm seeing...
console.log(cli.flags) // {}
console.log(cli.input) // []

// Same applies to...
const cli = meow(help, {argv: ['root', 'foo']})
const cli = meow(help, {argv: ['-r', 'foo']})

```

Any ideas?

**Comment by F1LT3R** [comment]
Interestingly, it does work this way... (when helps is supplied as an option)

```javascript
const cli = meow({
    help,
    argv: ['--root', 'foo']
})

console.log(cli.flags) // { root: 'foo' }
console.log(cli.input) // []
```

But does not work this way... (when help is a param)

```javascript
const cli = meow(help, {
    argv: ['--root', 'foo']
})

console.log(cli.flags) // {}
console.log(cli.input) // []
```

**Comment by sindresorhus** [comment]
You need to supply the exact format as `process.argv` including the first two arguments with the node binary.

**Comment by sindresorhus** [comment]
Why are you using that option? It's really only meant for testing or if you do any preprocessing of argv.

**Comment by F1LT3R** [comment]
Noted. Thanks

I am in fact using it for testing in a cli app.

I was hoping to also use it to instantiate the module in api-mode, but
perhaps that is unwise.
