### ISSUE TITLE
Help shortcut

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#6]
Currently, I do this in most CLI's without defining any other options:

```js
meow({
	help: [
		'Example',
		'  $ fullname',
		'  Sindre Sorhus'
	]
});
```

Maybe we should add a `help` shortcut?

```js
meow([
	'Example',
	'  $ fullname',
	'  Sindre Sorhus'
]);
```

So the first argument can either be the `help` or an object of options.

@kevva @arthurvr @shinnn Thoughts?

**Comment by arthurvr** [comment]
Would we then also support the string signature of `help`? Anyways, yes, I like this. I generally don't like any arguments hocus-pocus but this is actually a really common thing and it's not going to confuse people.

**Comment by sindresorhus** [comment]
> Would we then also support the string signature of help?

Yes

**Comment by arthurvr** [comment]
Sounds good to me! :+1:

**Comment by kevva** [comment]
> I generally don't like any arguments hocus-pocus but this is actually a really common thing and it's not going to confuse people.

Same here, but I'm okay with this as long as we keep it an `array`/`string` OR an `object` with options.

**Comment by bevacqua** [comment]
Hey guys, #8 was a breaking change for modules that still did `meow({ help: usage })`. I started getting errors in [`hit-that`](https://github.com/bevacqua/hit-that/blob/1767ffa42c7281b5f57d65b30963ea9ba68b1efe/cli.js#L9) because of it.

**Comment by kevva** [comment]
What errors did occur? Can't see how that change would affect existing behavior.

**Comment by bevacqua** [comment]
![](https://ton.twitter.com/1.1/ton/data/dm/652120437313392643/652120437359517696/Ti6lpPra.png)

My code was just `meow({ help: someBuffer })`, it worked great for a while on `3.1.0` but then broke at some point. Changing the code to `meow(someBuffer)` fixed it in the latest version.

**Comment by kevva** [comment]
Oh, I think you need to read the file `usage.txt` as `utf8`. `fs.readFile` reads them as buffers by default and `meow` don't accept that.

**Comment by sindresorhus** [comment]
Yup, per [docs](https://github.com/sindresorhus/meow#help) `string` or `boolean`. That it worked before was just an implementation detail as some native methods coerces buffers to strings.

**Comment by kevva** [comment]
The reason it works using `meow(buf)` is because it's neither treated as a `string` or an `array` and it's not in `opts.help` so it never gets there. I bet your `ht --help` doesn't work :).

**Comment by bevacqua** [comment]
`ht --help` does work. I'll update my usage to passing in a string anyways. Thanks
