### ISSUE TITLE
Spaces instead of tab in help

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/meow#64]
When using the help section you need to use tabs to indent not spaces. For example with a tab vs 4 spaces before `--background`.

Works
```
const cli = meow(`
	Usage
	  $ astro [input]
	Options
	  --help            Show help menu
	  --background      Start background importing
`);
```

Unaligned
```
const cli = meow(`
	Usage
	  $ astro [input]
	Options
	  --help            Show help menu
          --background      Start background importing
`);
```

@sindresorhus if this is intended feel free to close as I mainly opened this for others that come searching the issues section as to why their help section isn't aligned correctly.

**Comment by sindresorhus** [comment]
You can use spaces or tabs. Shouldn't make a difference. Meow will just strip the indent and re-add it. You're probably using the wrong amount of spaces.
