### ISSUE TITLE
Bundle dependencies

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meow#67]
I usually don't care to do this, but it would be nice if `meow` was simply one dependency as it would help the install time on lots of small CLIs.

Not exactly sure the best way to do this. It should be something that doesn't add any build-script for development, meaning, everything should be handled in a `prepublish` script.

Maybe [`npm-packager`](https://github.com/sheerun/npm-packer) or just build it with Webpack.

Suggestions and help welcome.

**Comment by bfred-it** [comment]
https://github.com/gajus/bundle-dependencies ?

**Comment by sindresorhus** [comment]
Yeah, I guess that tool would work too, although I don't like the manual steps in the "Publishing" section. Should really be handled by the tool.

**Comment by kevva** [comment]
Keep in mind that this will require a version bump every time we want to update the dependencies. Might not matter too much though since this already works pretty much perfectly in the current state.

I think `npm-packager` looked pretty good.

**Comment by sindresorhus** [comment]
@kevva Yes, but the dependencies of `meow` are pretty mature and stable, so I don't really think that's going to be a problem.

**Comment by kevva** [comment]
Did some digging into this. Since neither `webpack`or `browserify` support `module.parent` we can't use any of those two. The one drawback `npm-packer` had was that you had to manually build it, `cd` into the built directory and publish it from there.

**Comment by sindresorhus** [comment]
There's also: https://github.com/dominictarr/noderify

**Comment by sindresorhus** [comment]
Alternatively, https://github.com/zertosh/v8-compile-cache could also help startup performance without having to bundle dependencies.

**Comment by ianwalter** [comment]
@sindresorhus I feel like [zeit/ncc](https://github.com/zeit/ncc) would be a good choice for this.

**Comment by tunnckoCore** [comment]
Or [publish-packed](https://github.com/zkochan/publish-packed) by Pnpm creator. It seems good enough. But have some limitations and bugs, on which i'm working.

**Comment by sindresorhus** [comment]
@tunnckoCore I've looked at that before, but I've decided to go with `ncc`.

**Comment by tunnckoCore** [comment]
Good choice anyway :)

**Comment by brandonpittman** [comment]
@sindresorhus I tried rolling up a Meow CLI with `ncc` and it failed unless I edited one of Meow's core library files.

**Comment by sindresorhus** [comment]
>@sindresorhus I tried rolling up a Meow CLI with `ncc` and it failed unless I edited one of Meow's core library files.

@brandonpittman What failed? What did you have to edit?

**Comment by brandonpittman** [comment]
@sindresorhus 

In meow's `index.js`, I had to change the line about `module.parent.filename` to:

```js
let parentDir = ''
if (module.parent && module.parent.filename) {
  parentDir = path.dirname(module.parent.filename);
}
```

Then the ncc-built CLI will run. Otherwise, I get an error like this:

```sh
/Users/brandon-pittman/dev/gridtastic/dist/index.js:21107
const parentDir = path.dirname(module.parent.filename);
                                             ^

TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/Users/brandon-pittman/dev/gridtastic/dist/index.js:21107:46)
    at __webpack_require__ (/Users/brandon-pittman/dev/gridtastic/dist/index.js:23:30)
    at Object.<anonymous> (/Users/brandon-pittman/dev/gridtastic/dist/index.js:23491:14
```

**Comment by tunnckoCore** [comment]
@brandonpittman it's okay that ncc will probably run that way, but the bundle won't work properly (the CLIs built with that bundle)?

**Comment by NMinhNguyen** [comment]
@sindresorhus due to https://github.com/webpack/webpack/issues/20#issuecomment-7957912 would you be open to perhaps moving the bulk of `index.js` (without `module.parent`) into another file which would get bundled, and then `index.js` would import that file? Or maybe we can revisit the need for `module.parent`?

**Comment by NMinhNguyen** [comment]
Actually, I just noticed that https://github.com/sindresorhus/conf/blob/bbf4fd40e944146f63f40a06fe14a531dcf8e941/source/index.ts#L27 does

```ts
const parentDir = path.dirname(module.parent?.filename ?? '.');
```

Would it be acceptable to add this fallback to `meow` as well? That would resolve this `ncc` issue? Unless I'm misunderstanding what the fallback is for?
