### ISSUE TITLE
Flags containing hyphens are split and not parsed correctly

### ISSUE THREAD

**Issue by SirWindfield** [sindresorhus/meow#79]
I wanted to add some `--no-x` flags but meow doesn't handle them properly. Looks like they get split in the middle and aliased versions do not work either.

```javascript
{
    flags: {
      columns: {
        type: 'string',
        alias: 'c',
      },
      'no-color': {
        alias: 'nc',
        type: 'boolean',
      },
      'no-map': {
        alias: 'nm',
        type: 'boolean',
      },
    },
  },
```

Calling ```node index.js package.json --no-map --no-color --columns 16``` returns 
```javascript
{ noColor: false,
  nc: false,
  noMap: false,
  nm: false,
  map: false,
  color: false,
  columns: '16',
  c: '16',
}
```
instead of this (fields have been fixed too to resemble the actually passed ones):
```javascript
{ noColor: true,
  nc: true,
  noMap: true,
  nm: true,
  noColor: true,
  columns: '16',
  c: '16',
}
```

**Comment by SamVerschueren** [comment]
You get the `--no-color` out of the box if you define `color` as `boolean`. So you should make `color` and `map` a boolean and give them a default value of `true`.

**Comment by SirWindfield** [comment]
I didn't know this! Thank you!
