### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by zaynv** [sindresorhus/meow#86]
Instead of 

```js
meow(`
  Usage
    $ foo

  Options
    --bar  Does bar stuff.
    --baz  Does bax stuff.

 Examples
    $ foo
    $ foo --bar
    $ foo --baz
`, options)
```

what about

```js
meow(options)`
  Usage
    $ foo

  Options
    --bar  Does bar stuff.
    --baz  Does bax stuff.

 Examples
    $ foo
    $ foo --bar
    $ foo --baz
`
```

just suggestion, you can close if you dont want.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but that's an abuse of tagged template literals, and doesn't have any benefits over the current API. All you're doing is moving the template literal.
