### ISSUE TITLE
Flag alias with number not working

### ISSUE THREAD

**Issue by torifat** [sindresorhus/meow#89]
I want to support the following flag:

```
--stage-0, -0
```

But, `-0` doesn't work. `--0` is working. Is it by design? If it's not then I can raise a PR. Thanks for the awesome project ❤️

**Comment by sindresorhus** [comment]
Just an oversight. PR welcome :)

**Comment by torifat** [comment]
It turns out that the problem is with `yargs-parser`.

I/O with non-number alias

```
{ minimistoptions:
   { string: [ '_' ],
     boolean: [ 'zero' ],
     alias: { x: 'zero' },
     default: { zero: false } } }
```
```
{ argv: { _: [], zero: true, x: true } }
```

I/O with number alias
```
{ minimistoptions:
   { string: [ '_' ],
     boolean: [ 'zero' ],
     alias: { '0': 'zero' },
     default: { zero: false } } }
```
```
{ argv: { '0': false, _: [ '-0' ], zero: false } }
```

**Comment by sindresorhus** [comment]
Can you open an issue on `yargs-parser` about the problem?

**Comment by torifat** [comment]
> Can you open an issue on `yargs-parser` about the problem?

Done

**Comment by torifat** [comment]
Seems like it wasn't a mistake  -> yargs/yargs-parser#44
