### ISSUE TITLE
Throws when used with --experimental-modules

### ISSUE THREAD

**Issue by matthewp** [sindresorhus/meow#90]
If using an mjs module using --experimental-modules and importing `meow` it throws on this line:

https://github.com/sindresorhus/meow/blob/258659a6e4cf102ef09a7c27efcee1e953808725/index.js#L15

I think this might be the Node issue: https://github.com/nodejs/node/issues/15760

**Comment by sindresorhus** [comment]
Open an issue on Node.js. They'll need to create a replacement for `module.parent`. Closing as I don't intend to do anything for experimental features.

**Comment by matthewp** [comment]
According to that issue there won't be a replacement for `module.parent` in the case where a commonjs module is imported by an ES module. So if parentDir is required then this might need to change to be an ES module (although I'm not certain it would work the other way then). Anyways, something for another time as you prefer to wait for the feature to be out of experimental.
